Fix name regex
AY2122S2-CS2103T-W15-3/tp pull request #153
Opened 2022-04-06 08:11 UTC by jaysmyname

Change name to allow hyphens and apostrophes and disallow numbers
Restrict name character limit to 100

2022-04-06 16:41 UTC, LowJiaHao99 requested changes
Just 1 small change needed, as well as a clarifying question. Once the small issue is resolved, LGTM.

2022-04-06 16:41 UTC, LowJiaHao99 commented on src/main/java/seedu/address/model/student/Name.java
> +                    + "letters. Names cannot be blank and cannot be longer than 100 characters in total.";
Add `Can end with numbers` to sync with user guide

2022-04-07 02:38 UTC, jaysmyname commented on src/main/java/seedu/address/model/student/Name.java
> +    public static final String VALIDATION_REGEX = "[A-Za-z]([ '-]?[A-Za-z])*( \\d+)?";
Yes. See NameTest.java line 39

2022-04-07 12:31 UTC, vanessaxuuan commented on src/main/java/seedu/address/model/student/Name.java
> +                    + "letters. Names can end with numbers. Names cannot be blank and cannot be longer than "
Could edit to "Names must start with a letter but can end with numbers"?

2022-04-08 08:38 UTC, LowJiaHao99 approved these changes

2022-04-08 08:38 UTC, LowJiaHao99 commented
LGTM

2022-04-08 08:38 UTC, merged