Update ug bugs
AY2122S2-CS2103T-W15-3/tp pull request #163
Opened 2022-04-07 17:55 UTC by vanessaxuuan

Update UG

Fix documentation bugs in
- quick start
- findtg

Update documentations for `add`, `find` and `findtg` features

2022-04-08 00:47 UTC, LowJiaHao99 reviewed
One specification to check. May need changes to be done depending on result

2022-04-08 00:47 UTC, LowJiaHao99 commented on docs/UserGuide.md
> +* The search ignores extra whitespaces. e.g. `cs2101<><><>g08` will match `cs2101<>g08`
Just to check: Is this what the current findtg do? (Test it out in the program)

Was curious since there was no change to the code of findtg.

2022-04-08 00:49 UTC, LowJiaHao99 commented on docs/UserGuide.md
>  from the initial `List` [output](#listing-all-students-list)
Should this be `List` or `list`?

2022-04-09 07:21 UTC, jaysmyname requested changes
Small change required in the user guide

2022-04-09 07:21 UTC, jaysmyname commented on docs/UserGuide.md
> +  - Do manually differentiate them by saving them as `Sam1` and `Sam2` for easier reference.
Right now the functionality is that you need to put a space and then a number, so it needs to be "Sam 1" and "Sam 2"

2022-04-09 10:24 UTC, merged