Feature addtg
AY2122S2-CS2103T-W15-3/tp pull request #60
Opened 2022-03-19 18:51 UTC by vanessaxuuan

2022-03-20 03:57 UTC, LowJiaHao99 requested changes
Perhaps testcases can be added to check whether the class functions as expected?

2022-03-20 03:57 UTC, LowJiaHao99 commented on src/main/java/seedu/address/logic/commands/AddTutorialGroupCommand.java
> +public class AddTutorialGroupCommand extends Command {
Perhaps testcases can be added to test the functionality of the AddTutorialGroupCommand?

2022-03-20 03:57 UTC, LowJiaHao99 commented on src/main/java/seedu/address/logic/parser/AddTutorialGroupParser.java
> +public class AddTutorialGroupParser implements Parser<AddTutorialGroupCommand> {
Perhaps testcases can be added to test the functionality of the AddTutorialGroupParser?

2022-03-20 03:57 UTC, LowJiaHao99 commented on src/main/java/seedu/address/logic/commands/AddTutorialGroupCommand.java
> +            + "[" + PREFIX_TUTORIAL_GROUP + "TUTORIAL_GROUP]...\n"
addTutorialGroup cannot be be optional. Must have at least 1 tg/. 

Should the brackets be there?

2022-03-20 03:57 UTC, LowJiaHao99 commented on src/main/java/seedu/address/logic/commands/AddTutorialGroupCommand.java
> +        // identify duplicate modules
Should it be "tutorial groups" ?

2022-03-20 03:57 UTC, LowJiaHao99 commented on src/main/java/seedu/address/model/student/Student.java
> +    public Student addTutorialGroup(Set<TutorialGroup> toAdd) {
Student field values are immutable

Should tutorialGroup be modified?

How about consider instantiating a student with the modified tutorialGroups instead?

2022-03-20 03:57 UTC, LowJiaHao99 commented on src/main/java/seedu/address/model/student/Student.java
> +    public boolean tutorialGroupExists(Set<TutorialGroup> toCheck) {
Perhaps consider adding testcases to test the functionality of the method?

2022-03-20 03:57 UTC, LowJiaHao99 commented on src/main/java/seedu/address/logic/parser/AddressBookParser.java
> +        case AddTutorialGroupCommand.COMMAND_WORD:
Perhaps adding the testcase in AddressBookParser for this new command?

2022-03-20 03:57 UTC, LowJiaHao99 commented on src/main/java/seedu/address/logic/commands/AddTutorialGroupCommand.java
> +        return studentToEdit.addTutorialGroup(newTutorialGroups);
Student is immutable.

Perhaps create a new Student with the updated tutorial group descriptors?

2022-03-20 08:48 UTC, hqhqhq1 reviewed
test cases mentioned by Jia Hao

2022-03-20 08:48 UTC, hqhqhq1 commented on src/main/java/seedu/address/logic/commands/AddTutorialGroupCommand.java
> +            + "[" + PREFIX_TUTORIAL_GROUP + "TUTORIAL_GROUP]...\n"
For addStudentCommand, I didn't put in brackets for all prefixes, do we need to standardize it?

2022-03-20 08:48 UTC, hqhqhq1 commented on src/main/java/seedu/address/logic/commands/AddTutorialGroupCommand.java
> +    private static Student updateStudent(Student studentToEdit, AddTutorialGroupDescriptor addTutorialGroupDescriptor) {
maybe can name it as updateStudentTutorialGroup

2022-03-21 05:21 UTC, LowJiaHao99 requested changes
Minor issues, once resolved LGTM.

2022-03-21 05:21 UTC, LowJiaHao99 commented on src/main/java/seedu/address/logic/commands/AddTutorialGroupCommand.java
> +         * Returns an unmodifiable tag set, which throws {@code UnsupportedOperationException}
change tag to tutorial group

2022-03-21 05:21 UTC, LowJiaHao99 commented on src/test/java/seedu/address/testutil/AddTutorialGroupDescriptorBuilder.java
> +    public static final AddTutorialGroupDescriptor VALID_DESCRIPTOR_AMY =
Is VALID_TUTORIAL_GROUP_DESCRIPTOR_AMY more clear?

2022-03-21 05:21 UTC, LowJiaHao99 commented on src/test/java/seedu/address/testutil/AddTutorialGroupDescriptorBuilder.java
> +    public static final AddTutorialGroupDescriptor VALID_DESCRIPTOR_BOB =
Is VALID_TUTORIAL_GROUP_DESCRIPTOR_BOB more clear?

2022-03-21 14:43 UTC, LowJiaHao99 approved these changes

2022-03-21 15:14 UTC, hqhqhq1 approved these changes

2022-03-21 15:32 UTC, merged